config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'poll#new'
  get  'poll/new'
  post 'poll/create'
  get  'poll/create', to: 'poll#new'
  get  'poll/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  FRAMEWORK_ATTRS = %w(id created_at updated_at)
end

app/models/poll.rb
class Poll < ApplicationRecord
  # Constants
  TEXT_ATTRS = %w(name email phone open_question)
  BOOL_ATTRS = Poll.column_names - TEXT_ATTRS - FRAMEWORK_ATTRS

  # Callbacks
  before_save :strip_text_data

  # Validations
  validates :name, allow_blank: true,
                   length: {maximum: 255}

  ##TODO: Internacionalizar mensaje en validaciones
  validates :email, allow_blank: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP,
                    message: "%{value} has an invalid email format" }

  validates :phone, allow_blank: true,
                    length: {is: 7},
                    numericality: { only_integer: true }

  validates :answer1,
            :answer2,
            :answer3,
            :answer4,
            :answer5,
            :answer6,
            :answer7,
            :answer8,
            :answer9,
            :answer10,
            :answer11,
            inclusion: { in: [true, false] }

  validates :open_question, length: {maximum: 65535}

  # Scopes
  scope :count_answer, ->(answer) { where({ answer => true}).count }

  # Instance methods
  def strip_text_data
    name.strip unless name.nil?
    email.strip unless email.nil?
    phone.strip unless phone.nil?
    open_question.strip unless open_question.nil?
  end

  # Class methods
  def self.format_params(params)
    formated_params = {}

    # Handle text attributes
    TEXT_ATTRS.each do |t|
      formated_params[t] = params[t]
    end

    # Handle boolean attributes
    TEXT_ATTRS.each { |t| params.delete t }
    BOOL_ATTRS.each do |b|
      formated_params[b] = params.values.include? b
    end
    formated_params
  end

  def self.results
    results = {}
    1.upto 11 do |i|
      results["answer#{i}".to_sym] = count_answer("answer#{i}".to_sym)
    end
    results
  end

  def self.seed(quantity = 100)
    polls = []
    bool_values = [true, false]
    quantity.times do
      polls << { name: Faker::Name.name,
                 email: Faker::Internet.email,
                 phone: rand(1111111..9999999),
                 answer1: bool_values.sample,
                 answer2: bool_values.sample,
                 answer3: bool_values.sample,
                 answer4: bool_values.sample,
                 answer5: bool_values.sample,
                 answer6: bool_values.sample,
                 answer7: bool_values.sample,
                 answer8: bool_values.sample,
                 answer9: bool_values.sample,
                 answer10: bool_values.sample,
                 answer11: bool_values.sample,
                 open_question: Faker::Lorem.paragraph(sentence_count: 20) }
    end
    Poll.create polls
  end

  private :strip_text_data
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  I18n.locale = :es
end

app/controllers/poll_controller.rb
class PollController < ApplicationController

  # GET /poll/new
  ##TODO: Utilizar elos helpers del form_with
  ##TODO crear partial de errores e internacionalizar plural de errores
  def new
    @poll = Poll.new
  end

  # POST /poll/create
  def create
    @poll = Poll.new(format_params)
    if @poll.save
      redirect_to poll_index_url, notice: t('success_survey')
    else
      render :new
    end
  end

  # GET /poll/index
  ##TODO: Craer una pagina especifica que muestre los resultados
  def index
   @results = Poll.results
  end

  private

  def format_params
    Poll.format_params(permit_poll_params)
  end

  # Only allow a list of trusted parameters through.
  def permit_poll_params
    params.permit(:name,
                  :email,
                  :phone,
                  :select,
                  :radio,
                  :checkbox1,
                  :checkbox2,
                  :checkbox3,
                  :open_question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poll_helper.rb
module PollHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:page_title) ? yield(:page_title) : 'Cocoweb' %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/poll/index.html.erb
<% content_for :page_title do %>
    Cocoweb - Poll results
<% end %>

<header>
  <a href="http://www.presidencia.gob.ve/Site/Web/Principal/paginas/classVice_Suprema_Felicidad_Social_Pueblo.php" target="_blank">
    <img id="header-pic" src="https://imgur.com/dZHnpG7.png" />
  </a>
</header>

<main>
  <div class="poll_flash">
    <%= flash[:notice] %>
  </div>

  <div id="title-group">
   <h1 id="title">
   R.E.M.E.V.S.F.S.P.M.P.P.D.P.S.G.G.
   </h1>
   <p id="description">
   Respuestas a la Encuesta de Misión Encuesta del Viceministerio para la Suprema Felicidad del Pueblo, parte del Ministerio del Poder Popular del Despacho de la Presidencia y Seguimiento de la Gestión de Gobierno
   </p>
  </div>

  <div class="content">
    <div class="question-group">
        <p id="feliz" class="question">
        ¿Por qué eres feliz?
        </p>
          <ul>
            <li>
            El comandante eterno tocó mi corazón: <%= @results[:answer1] %>
            </li>
            <li>
            Recibo mi CLAP casi siempre que obedezco: <%= @results[:answer2] %>
            </li>
            <li>
            Sé que los burguesitos la están pasando mal: <%= @results[:answer3] %>
            </li>
            <li>
            Vivo en Venezuela, es la tierra donde nació Bolívar: <%= @results[:answer4] %>
            </li>
            <li>
            A pesar de todo lo que El Pueblo ha hecho por mí, soy infeliz: <%= @results[:answer5] %>
            </li>
          </ul>
    </div>  <!-- cierre pregunta 1-->
    <div class="question-group">
        <p class="question">
        Según tu oponión, ¿cuál es el origen de la infelicidad?
        </p>
          <ul>
            <li>
            La ignorancia de creer en el capitalismo salvaje: <%= @results[:answer6] %>
            </li>
            <li>
            El dolor de saber que Chávez se fue muy pronto: <%= @results[:answer1] %>
            </li>
            <li>
            Ser escuálido: <%= @results[:answer8] %>
            </li>
          </ul>
    </div> <!-- cierre pregunta 2-->
    <div class="question-group">
        <p class="question">
        ¿Qué haces para ayudar a conseguir la suprema felicidad de El Pueblo?
        </p>
        <ul>
          <li>
          Voto cada vez que mi revolución lo necesita: <%= @results[:answer9] %>
          </li>
          <li>
          Mantengo informados a mis camaradas cuando no tienen luz o no pueden ver VTV: <%= @results[:answer10] %>
          </li>
          <li>
          Mantengo informadas a las autoridades sobre lo que hacen mis camaradas: <%= @results[:answer11] %>
          </li>
        </ul>
    </div>  <!-- cierre pregunta 3-->
  </div>

   <!--<div class="question-group">
   ¿Cómo te haría sentir si esta encuesta no llegara a ser leída nunca?
   </div>-->
</main>

app/views/poll/new.html.erb
<header>
  <a href="http://www.presidencia.gob.ve/Site/Web/Principal/paginas/classVice_Suprema_Felicidad_Social_Pueblo.php" target="_blank">
    <img id="header-pic" src="https://imgur.com/dZHnpG7.png" >
  </a>
</header>

<main>
  <div class="poll_errors">
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>
        <ul>
          <% @poll.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  </div>

  <div id="title-group">
    <h1 id="title">
    M.E.V.S.F.S.P.M.P.P.D.P.S.G.G.
    </h1>

    <p id="description">
    Misión Encuesta del Viceministerio para la Suprema Felicidad del Pueblo, parte del Ministerio del Poder Popular del Despacho de la Presidencia y Seguimiento de la Gestión de Gobierno
    </p>
  </div>

  <%= form_with url: poll_create_path, id: 'survey-form', class: :content do |_form| %>
    <div class="question-group">
      <label id="name-label" class="question" for="name">
      nombre
      </label>

      <input
      id="name"
      type="text"
      placeholder="Introduzca su nombre aquí"
      name="name"
      value="<%= @poll.name %>"
      required
      >
    </div>

    <div class="question-group">
      <label id="email-label" class="question" for="email">correo electrónico</label>
      <input
        id="email"
        type="email"
        placeholder="Introduzca su correo aquí"
        name="email"
        value="<%= @poll.email %>"
        required>
    </div>

    <div class="question-group">
      <label id="number-label" class="question" for="number">
      número de teléfono
      </label>

      <input
      id="number"
      type="number"
      min="1111111"
      max="9999999"
      placeholder="Introduzca su número aquí"
      name="phone"
      value="<%= @poll.phone %>"
      >
    </div>

    <div class="question-group">
      <label id="dropdown-label" class="question" for="dropdown">
      ¿Por qué eres feliz?
      </label>

      <select
      id="dropdown"
      placeholder="DROPDOWN"
      name="select">
        <option disabled selected>
        elija una opción
        </option>

        <option value="answer1">
        El comandante eterno tocó mi corazón.
        </option>

        <option value="answer2">
        Recibo mi CLAP casi siempre que obedezco.
        </option>

        <option value="answer3">
        Sé que los burguesitos la están pasando mal.
        </option>

        <option value="answer4">
        Vivo en Venezuela, es la tierra donde nació Bolívar.
        </option>

        <option value="answer5">
        A pesar de todo lo que El Pueblo ha hecho por mí, soy infeliz.
        </option>
      </select>
    </div>

    <div class="question-group">
      <p class="question">Según tu oponión, ¿cuál es el origen de la infelicidad?</p>

      <label for="capitalismo" class="radiocheck-label">
        <input
        id="capitalismo"
        type="radio"
        name="radio"
        value="answer6">
      La ignorancia de creer en el capitalismo salvaje.
      </label>

      <label for="chavez" class="radiocheck-label">
        <input
        id="chavez"
        type="radio"
        name="radio"
        value="answer7">
      El dolor de saber que Chávez se fue muy pronto.
      </label>

      <label for="escualido" class="radiocheck-label">
        <input
        id="escualido"
        type="radio"
        name="radio"
        value="answer8">
      Ser escuálido.
      </label>
    </div>

    <div class="question-group">
      <p class="question">¿Qué haces para ayudar a conseguir la suprema felicidad de El Pueblo?</p>
      <label for="votar" class="radiocheck-label">
        <input
        id="votar"
        type="checkbox"
        name="checkbox1"
        value="answer9">
      Voto cada vez que mi revolución lo necesita.
      </label>

      <label for="comunicar" class="radiocheck-label">
        <input
        id="comunicar"
        type="checkbox"
        name="checkbox2"
        value="answer10">
      Mantengo informados a mis camaradas cuando no tienen luz o no pueden ver VTV.
      </label>

      <label for="sapear" class="radiocheck-label">
        <input
        id="sapear"
        type="checkbox"
        name="checkbox3"
        value="answer11">
      Mantengo informadas a las autoridades sobre lo que hacen mis camaradas.
      </label>
    </div>

    <div class="question-group">
      <label for="sentir" class="question">
      ¿Cómo te haría sentir si esta encuesta no llegara a ser leída nunca?
      </label>

      <textarea placeholder="Escribe tu respuesta aquí" name="open_question"></textarea>
    </div>

    <div>
      <button
        type="submit"
        id="submit">Enviar
      </button>
    </div>
  <% end %>

</main>